---
title: "Welcome to Calculus"
author: "Math 111"
date: "Aug 30, 2017"
output: 
  ioslides_presentation: 
    incremental: yes
    widescreen: yes
---

## Introductions
- Get a note card
- Find a stranger
  - Name
  - Major
  - An interest
  - Something you're good at

## More Introductions
- Find a new pair of strangers
- Introduce your new friend to them

## More About Those Things You're Good At...
- Let's make a list

## The Course Website
- Haiku
  - Check it out
  
## Modeling Disease: SIR
The populations:
- S - susceptible
- I - infected
- R - recovered

## The Setup
- We start with 7 Infected, everyone else is susceptible
  - keep your identity secret!
- We'll mingle, then find a partner.
- Pairs play rock paper scissors.
  - S/I: If the sick person wins, the susceptible become infected. The susceptible write down the day they became infected.
  - S/S: Nothing
  - I/I: Nothing
- Starting on day 3, infected will recover. (e.g. if you started infected, you recover after 3 days, etc.)

## The Setup
- Record each day and your state each day!
- I'll record results at the end

## What happened?
What might this look like as a graph?

How to S, I, and R interact?



<!-- ernst What are the goals of a college education?
How does a person learn something new?
What do you reasonable expect to remember from your courses in
20 years?
What is the value of making mistakes in the learning process?
How do we create a safe environment where risk-taking is
encouraged and productive failure is valued?


-->
