---
title: "Day 2"
author: "Math 111"
date: "August 29, 2017"
output: ioslides_presentation
---

## Day 2
author: Math 111
date: 
autosize: true

## Course Organization
- Syllabus
- Learning goals
- Haiku

## A Quote
"The grading system for this calculus class is likely different than anything you have seen in your classes before. At first it will seem like the website used and the way grades are determined make no sense, but at the end of the class you will see the benefits. First of all, the Haiku website can prove to be more comprehensive than Sakai if you take a moment to figure it out. As for the grades themselves, everything is broken down into topics covered in the class. The rubric you received for your grades mentions these “learning goals” along with videos and labs. You have to master a set number of learning goals for an A, and certain numbers for lower grades. However, the beauty of the grading system is a balance between the learning goals, videos, labs, etc.

## Continued

On tests and homework assignments, questions are designated with the associated learning goals, and correctly answering them will lead you to a mastery of that learning goal. When it comes time for the final, the exam is tailored to you specifically. Any learning goals you have already mastered will not be on the exam and you can choose the learning goals you want to still master to be included on the test. Focus on the learning goals, and don’t stress about the ones you don’t master. You will have an opportunity to do so. Do your assignments and study and you’ll do great. Take it from me, a student whose grade was a D- at midterms and an A- at finals, your grade can be saved.